name: checks

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: pip install -r requirements.txt
      - run: flake8 src
      - run: black --check src
      - run: isort --check src
      - run: mypy src
